export interface SentenceData {
  id: string;
  text: string;
}

// NOTE: Audio is now generated by the browser's Text-to-Speech engine.
export const pteRepeatSentenceData: SentenceData[] = [
  { id: 'rs1', text: 'The university will seek a colossal renovation to the plain-looking theater.' },
  { id: 'rs2', text: 'Please remember to bring a highlighter and your textbook to class next Thursday.' },
  { id: 'rs3', text: 'The library is located on the north side of the campus.' },
  { id: 'rs4', text: 'The financial report for the last quarter will be available this afternoon.' },
  { id: 'rs5', text: 'Climate change is a global issue that requires immediate and collective action.' },
];
