export interface LectureData {
  id: string;
  title: string;
  transcript: string;
}

// NOTE: Audio is now generated by the browser's Text-to-Speech engine.
export const pteRetellLectureData: LectureData[] = [
  {
    id: 'rl1',
    title: 'The Urban Heat Island Effect',
    transcript: 'The "urban heat island" effect is a phenomenon where metropolitan areas are significantly warmer than their surrounding rural areas. This is primarily caused by human activities. Materials like concrete and asphalt absorb and retain more solar radiation than natural landscapes. Additionally, waste heat from buildings, vehicles, and industrial processes contributes to the higher temperatures. This effect can have significant impacts on energy consumption, air quality, and human health.',
  },
  {
    id: 'rl2',
    title: 'The Development of Antibiotic Resistance',
    transcript: 'Antibiotic resistance is a major global health crisis. It occurs when bacteria change in response to the use of these medicines. Overuse and misuse of antibiotics in humans and animals are accelerating the process. When bacteria become resistant, standard treatments become ineffective, infections persist, and may spread to others. Without urgent action, we are heading for a post-antibiotic era, in which common infections and minor injuries can once again kill.',
  },
];
