'use client';
import Link from 'next/link';
import Image from 'next/image';
import { useSyncExternalStore, type CSSProperties } from 'react';
import { ArrowUpRight, ArrowRight, Headphones, BookOpen, PenLine, Mic, Check, Clock3, Layers3, Sparkles } from 'lucide-react';
import { ieltsSkills } from '@/lib/ielts-catalog';
const icons = { listening: Headphones, reading: BookOpen, writing: PenLine, speaking: Mic };
let visitTrack = 'academic';
function readTrack() { try { return localStorage.getItem('ielts-track') || visitTrack; } catch { return visitTrack; } }
function subscribeTrack(callback: () => void) { window.addEventListener('storage', callback); window.addEventListener('ielts-track-change', callback); return () => { window.removeEventListener('storage', callback); window.removeEventListener('ielts-track-change', callback); }; }
export function IeltsStudio({ section }: { section?: string }) {
  const track = useSyncExternalStore(subscribeTrack, readTrack, () => 'academic');
  function chooseTrack(value: 'academic' | 'general') { visitTrack = value; try { localStorage.setItem('ielts-track', value); } catch { /* Keep the choice for this visit. */ } window.dispatchEvent(new Event('ielts-track-change')); }
  const skill = ieltsSkills.find(item => item.id === section);
  const isGeneral = track === 'general';
  const groups = skill?.id === 'writing' && isGeneral ? ['Task 1 · Letter', 'Task 2 · Essay'] : skill?.id === 'reading' && isGeneral ? ['Section 1 · Everyday reading', 'Section 2 · Workplace reading', 'Section 3 · Extended reading'] : skill?.groups;
  const types = skill?.id === 'writing' && isGeneral ? ['Formal letters', 'Semi-formal letters', 'Informal letters', 'Opinion essays', 'Discussion essays', 'Multi-part essays'] : skill?.types;
  return <div className="studio-wrap">
    <div className="studio-top"><Link href="/dashboard/ielts" className="studio-wordmark">IELTS <span>STUDIO</span><i /></Link><span className="studio-top-note">A little practice. A world of possibility.</span></div>
    <nav className="studio-nav" aria-label="IELTS sections">{[{ id: '', title: 'Overview' }, ...ieltsSkills, { id: 'mock-tests', title: 'Mock tests' }].map(item => <Link key={item.id} aria-current={(section || '') === item.id ? 'page' : undefined} href={`/dashboard/ielts${item.id ? `/${item.id}` : ''}`}>{item.title}</Link>)}</nav>
    <div className="studio-track-row"><span>YOUR STUDY PATH</span><div className="studio-track" role="group" aria-label="Test type"><button aria-pressed={!isGeneral} onClick={() => chooseTrack('academic')}>Academic</button><button aria-pressed={isGeneral} onClick={() => chooseTrack('general')}>General Training</button></div></div>
    {!section ? <>
      <section className="studio-hero"><div className="studio-hero-copy"><p className="studio-eyebrow">YOUR NEXT CHAPTER STARTS HERE</p><h1>Small steps.<br /><em>Wider horizons.</em></h1><p>A space to find your confidence in English. Explore the four skills and make your next study session count.</p><Link className="studio-primary" href="/ai-ielts-essay-practice">Practise Writing Task 2 <ArrowUpRight size={18} /></Link><span className="studio-caption"><span /> Essay practice available now</span></div><div className="studio-art"><Image src="/images/ielts/studio-hero-ielts-red.png" alt="" fill priority sizes="(max-width: 760px) 100vw, 50vw" /><div className="studio-art-label">LEARN WITH PURPOSE <span>✦</span></div></div></section>
      <div className="studio-section-title"><div><p className="studio-eyebrow">FOUR SKILLS. ONE JOURNEY.</p><h2>Where will you begin?</h2></div><span>Explore your practice spaces</span></div>
      <div className="studio-skills">{ieltsSkills.map((item, i) => { const Icon = icons[item.id]; return <Link href={`/dashboard/ielts/${item.id}`} key={item.id} className="studio-skill" style={{ '--skill-color': item.color, '--skill-tint': item.tint } as CSSProperties}><div className="studio-skill-top"><span className="studio-skill-icon"><Icon size={27} strokeWidth={1.5} /></span><span>0{i + 1}</span></div><h3>{item.title}</h3><p>{item.subtitle}</p><div className="studio-skill-bottom"><span>{item.id === 'writing' ? 'Task 2 available' : 'Preview the section'}</span><ArrowUpRight size={19} /></div></Link>; })}</div>
      <div className="studio-bottom-grid"><section className="studio-note"><span className="studio-eyebrow">A GOOD PLACE TO START</span><h2>One essay.<br />A clearer next step.</h2><p>Write a Task 2 response and explore AI feedback on your ideas, organisation, vocabulary and grammar.</p><Link href="/ai-ielts-essay-practice">Open the essay trainer <ArrowRight size={17} /></Link><small>AI feedback is a practice estimate. Scoring may require credits.</small></section><section className="studio-roadmap"><p className="studio-eyebrow">THE STUDIO IS GROWING</p><h2>More ways to practise, on the way.</h2><div><Check size={18} /><span><strong>Writing Task 2</strong>Available to practise today</span><b>LIVE</b></div><div><Layers3 size={18} /><span><strong>Skill question collections</strong>New practice is being prepared</span></div><div><Clock3 size={18} /><span><strong>Timed mock tests</strong>Coming after the skill collections</span></div></section></div>
    </> : skill ? <>
      <section className="studio-detail-hero" style={{ '--skill-color': skill.color, '--skill-tint': skill.tint } as CSSProperties}><p className="studio-eyebrow">{isGeneral ? 'GENERAL TRAINING' : 'ACADEMIC'} · {skill.title.toUpperCase()}</p><h1>{skill.subtitle}</h1><p>{skill.description}</p><span className="studio-detail-label">{skill.id === 'listening' || skill.id === 'speaking' ? 'Shared by Academic and General Training' : `${isGeneral ? 'General Training' : 'Academic'} practice path`}</span></section>
      <div className="studio-section-title"><div><p className="studio-eyebrow">YOUR PRACTICE COLLECTION</p><h2>{skill.title} sections</h2></div></div>
      {skill.id === 'reading' && !isGeneral ? <div className="studio-parts">
        <section className="studio-part"><span className="studio-part-number">01</span><div><h3>Cambridge IELTS 11 · Academic Reading Test 1</h3><p>Three passages · 40 questions · diagram labelling, completion and matching · answer review</p></div><Link className="studio-primary" href="/dashboard/ielts/reading/cambridge-11-test-1">Start practice <ArrowUpRight size={16} /></Link></section>
        <section className="studio-part"><span className="studio-part-number">02</span><div><h3>Cambridge IELTS 11 · Academic Reading Test 2</h3><p>Three passages · 40 questions · True/False/Not Given, paragraph headings, diagram, summary and multiple choice · answer review</p></div><Link className="studio-primary" href="/dashboard/ielts/reading/cambridge-11-test-2">Start practice <ArrowUpRight size={16} /></Link></section>
        <section className="studio-part"><span className="studio-part-number">03</span><div><h3>Cambridge IELTS 11 · Academic Reading Test 3</h3><p>Three passages · 40 questions · notes and sentence completion, sentence endings, section matching and True/False/Not Given · answer review</p></div><Link className="studio-primary" href="/dashboard/ielts/reading/cambridge-11-test-3">Start practice <ArrowUpRight size={16} /></Link></section>
        <section className="studio-part"><span className="studio-part-number">04</span><div><h3>Cambridge IELTS 11 · Academic Reading Test 4</h3><p>Three passages · 40 questions · True/False/Not Given, matching researchers, multiple choice, matching headings and summary completion · answer review</p></div><Link className="studio-primary" href="/dashboard/ielts/reading/cambridge-11-test-4">Start practice <ArrowUpRight size={16} /></Link></section>
        <section className="studio-part"><span className="studio-part-number">05</span><div><h3>Cambridge IELTS 12 · Academic Reading Test 1</h3><p>Three passages · 40 questions · True/False/Not Given, notes and sentence completion, matching headings and summary completion · answer review</p></div><Link className="studio-primary" href="/dashboard/ielts/reading/cambridge-12-test-1">Start practice <ArrowUpRight size={16} /></Link></section>
        <section className="studio-part"><span className="studio-part-number">06</span><div><h3>Cambridge IELTS 12 · Academic Reading Test 2</h3><p>Three passages · 40 questions · locating information, matching people, choose-two, matching headings, table and sentence completion · answer review</p></div><Link className="studio-primary" href="/dashboard/ielts/reading/cambridge-12-test-2">Start practice <ArrowUpRight size={16} /></Link></section>
        <section className="studio-part"><span className="studio-part-number">07</span><div><h3>Cambridge IELTS 12 · Academic Reading Test 3</h3><p>Three passages · 40 questions · matching headings, notes completion, locating information, summary completion and multiple choice · answer review</p></div><Link className="studio-primary" href="/dashboard/ielts/reading/cambridge-12-test-3">Start practice <ArrowUpRight size={16} /></Link></section>
        <section className="studio-part"><span className="studio-part-number">08</span><div><h3>Cambridge IELTS 12 · Academic Reading Test 4</h3><p>Three passages · 40 questions · notes completion, multiple choice, summary completion and matching headings · answer review</p></div><Link className="studio-primary" href="/dashboard/ielts/reading/cambridge-12-test-4">Start practice <ArrowUpRight size={16} /></Link></section>
      </div> : <div className="studio-parts">{groups?.map((group, i) => { const live = skill.id === 'writing' && i === 1; return <section className="studio-part" key={group}><span className="studio-part-number">0{i + 1}</span><div><h3>{group}</h3><p>{live ? 'Develop your essay and receive AI practice feedback.' : 'Questions for this section are being prepared.'}</p></div>{live ? <Link className="studio-primary" href="/ai-ielts-essay-practice">Start practice <ArrowUpRight size={16} /></Link> : <span className="studio-soon">Coming soon</span>}</section>; })}</div>}
      <section className="studio-types"><h2>What you’ll practise</h2><div>{types?.map(type => <span key={type}>{type}</span>)}</div><p>These are the planned practice categories. Question collections will appear here as they become available.</p></section>
      {skill.id !== 'writing' && !(skill.id === 'reading' && !isGeneral) && <section className="studio-empty"><Sparkles size={24} /><h2>Your next practice collection is on its way.</h2><p>While we prepare these questions, you can start building your writing confidence.</p><Link href="/ai-ielts-essay-practice">Try Writing Task 2 <ArrowRight size={17} /></Link></section>}
    </> : <section className="studio-empty studio-mock"><Clock3 size={38} /><p className="studio-eyebrow">IELTS MOCK TESTS</p><h1>Bring your skills together.</h1><p>Timed section tests and full practice tests are being prepared. They’ll appear here when the questions and review tools are ready.</p><span className="studio-soon">Coming soon</span><Link href="/dashboard/ielts/writing">Explore writing practice <ArrowRight size={17} /></Link></section>}
    <footer className="studio-footer"><span>SMARTLABS · IELTS STUDIO</span><span>Your pace. Your progress. Your next chapter.</span></footer>
  </div>;
}
