import 'server-only';

// Answer key for Cambridge IELTS 12 · Academic Reading Test 3, transcribed from
// the owner-supplied material. Matching is case/whitespace-insensitive and
// accepts the listed variants (see grading.ts).
export const answerKey: Record<string, string[]> = {
  "1": ["v"],
  "2": ["iii"],
  "3": ["viii"],
  "4": ["i"],
  "5": ["iv"],
  "6": ["vi"],
  "7": ["ii"],
  "8": ["pirates"],
  "9": ["food"],
  "10": ["oil"],
  "11": ["settlers"],
  "12": ["species"],
  "13": ["eggs"],
  "14": ["D"],
  "15": ["C"],
  "16": ["F"],
  "17": ["G"],
  "18": ["D"],
  "19": ["B"],
  "20": ["vaccinations"],
  "21": ["antibiotics"],
  "22": ["mosquitos", "mosquitoes"],
  "23": ["factories"],
  "24": ["forests"],
  "25": ["polio"],
  "26": ["mountain"],
  "27": ["dopamine"],
  "28": ["pleasure"],
  "29": ["caudate"],
  "30": ["anticipatory phase"],
  "31": ["food"],
  "32": ["B"],
  "33": ["C"],
  "34": ["A"],
  "35": ["B"],
  "36": ["D"],
  "37": ["F"],
  "38": ["B"],
  "39": ["E"],
  "40": ["C"]
};
