import 'server-only';

// Answer key for Cambridge IELTS 13 · Academic Reading Test 1, transcribed from
// the owner-supplied material. Matching is case/whitespace-insensitive and
// accepts the listed variants (see grading.ts).
export const answerKey: Record<string, string[]> = {
  "1": ["update"],
  "2": ["environment"],
  "3": ["captain"],
  "4": ["films"],
  "5": ["season"],
  "6": ["accommodation"],
  "7": ["blog"],
  "8": ["FALSE"],
  "9": ["NOT GIVEN"],
  "10": ["FALSE"],
  "11": ["TRUE"],
  "12": ["NOT GIVEN"],
  "13": ["TRUE"],
  "14": ["iv"],
  "15": ["vi"],
  "16": ["i"],
  "17": ["v"],
  "18": ["viii"],
  "19": ["iii"],
  "20": ["E"],
  "21": ["B"],
  "22": ["D"],
  "23": ["A"],
  "24": ["focus"],
  "25": ["pleasure"],
  "26": ["curiosity"],
  "27": ["A"],
  "28": ["C"],
  "29": ["C"],
  "30": ["D"],
  "31": ["A"],
  "32": ["D"],
  "33": ["A"],
  "34": ["E"],
  "35": ["C"],
  "36": ["G"],
  "37": ["B"],
  "38": ["YES"],
  "39": ["NOT GIVEN"],
  "40": ["NO"]
};
