import 'server-only';

// Answer key for Cambridge IELTS 15 · Academic Reading Test 3, transcribed from
// the owner-supplied material. Matching is case/whitespace-insensitive and
// accepts the listed variants (see grading.ts).
export const answerKey: Record<string, string[]> = {
  "1": ["TRUE"],
  "2": ["FALSE"],
  "3": ["NOT GIVEN"],
  "4": ["TRUE"],
  "5": ["NOT GIVEN"],
  "6": ["FALSE"],
  "7": ["TRUE"],
  "8": ["resignation"],
  "9": ["materials"],
  "10": ["miners"],
  "11": ["family"],
  "12": ["Collectors"],
  "13": ["income"],
  "14": ["iii"],
  "15": ["vi"],
  "16": ["v"],
  "17": ["x"],
  "18": ["iv"],
  "19": ["viii"],
  "20": ["i"],
  "21": ["wheels"],
  "22": ["film"],
  "23": ["filter"],
  "24": ["waste"],
  "25": ["performance"],
  "26": ["servicing"],
  "27": ["C"],
  "28": ["B"],
  "29": ["F"],
  "30": ["A"],
  "31": ["E"],
  "32": ["D"],
  "33": ["F"],
  "34": ["B"],
  "35": ["C"],
  "36": ["G"],
  "37": ["B"],
  "38": ["D"],
  "39": ["A"],
  "40": ["A"]
};
