import 'server-only';

// Answer key for Cambridge IELTS 18 · Academic Reading Test 3, transcribed from
// the owner-supplied material. Matching is case/whitespace-insensitive and
// accepts the listed variants (see grading.ts).
export const answerKey: Record<string, string[]> = {
  "1": ["G"],
  "2": ["D"],
  "3": ["C"],
  "4": ["F"],
  "5": ["architects"],
  "6": ["moisture"],
  "7": ["layers"],
  "8": ["speed"],
  "9": ["C"],
  "10": ["A"],
  "11": ["B"],
  "12": ["D"],
  "13": ["A"],
  "14": ["iii"],
  "15": ["viii"],
  "16": ["vi"],
  "17": ["v"],
  "18": ["vii"],
  "19": ["i"],
  "20": ["iv"],
  "21": ["A"],
  "22": ["C"],
  "23": ["B"],
  "24": ["speed"],
  "25": ["fifty", "50"],
  "26": ["strict"],
  "27": ["B"],
  "28": ["A"],
  "29": ["C"],
  "30": ["C"],
  "31": ["H"],
  "32": ["D"],
  "33": ["F"],
  "34": ["E"],
  "35": ["B"],
  "36": ["NO"],
  "37": ["NOT GIVEN"],
  "38": ["YES"],
  "39": ["NO"],
  "40": ["NOT GIVEN"]
};
