import 'server-only';

// Answer key for Cambridge IELTS 14 · Academic Reading Test 3, transcribed from
// the owner-supplied material. Matching is case/whitespace-insensitive and
// accepts the listed variants (see grading.ts).
export const answerKey: Record<string, string[]> = {
  "1": ["B"],
  "2": ["A"],
  "3": ["D"],
  "4": ["NOT GIVEN"],
  "5": ["NO"],
  "6": ["YES"],
  "7": ["B"],
  "8": ["C"],
  "9": ["B"],
  "10": ["A"],
  "11": ["A"],
  "12": ["C"],
  "13": ["A"],
  "14": ["C"],
  "15": ["H"],
  "16": ["A"],
  "17": ["F"],
  "18": ["I"],
  "19": ["B"],
  "20": ["E"],
  "21": ["B", "C"],
  "22": ["B", "C"],
  "23": ["ecology"],
  "24": ["prey"],
  "25": ["habitats"],
  "26": ["antibiotics"],
  "27": ["B"],
  "28": ["G"],
  "29": ["F"],
  "30": ["E"],
  "31": ["C"],
  "32": ["NO"],
  "33": ["YES"],
  "34": ["NOT GIVEN"],
  "35": ["NO"],
  "36": ["YES"],
  "37": ["encouraging"],
  "38": ["desire"],
  "39": ["autonomy"],
  "40": ["targeted"]
};
