import 'server-only';

// Answer key for Cambridge IELTS 16 · Academic Reading Test 2, transcribed from
// the owner-supplied material. Matching is case/whitespace-insensitive and
// accepts the listed variants (see grading.ts).
export const answerKey: Record<string, string[]> = {
  "1": ["TRUE"],
  "2": ["NOT GIVEN"],
  "3": ["TRUE"],
  "4": ["FALSE"],
  "5": ["FALSE"],
  "6": ["TRUE"],
  "7": ["TRUE"],
  "8": ["NOT GIVEN"],
  "9": ["Ridgeway"],
  "10": ["documents"],
  "11": ["soil"],
  "12": ["fertility"],
  "13": ["Rhiannon"],
  "14": ["D"],
  "15": ["C"],
  "16": ["A"],
  "17": ["G"],
  "18": ["B"],
  "19": ["H"],
  "20": ["E"],
  "21": ["YES"],
  "22": ["NO"],
  "23": ["NOT GIVEN"],
  "24": ["YES"],
  "25": ["NOT GIVEN"],
  "26": ["NO"],
  "27": ["B"],
  "28": ["C"],
  "29": ["B"],
  "30": ["D"],
  "31": ["D"],
  "32": ["A"],
  "33": ["C"],
  "34": ["F"],
  "35": ["G"],
  "36": ["FALSE"],
  "37": ["NOT GIVEN"],
  "38": ["NOT GIVEN"],
  "39": ["TRUE"],
  "40": ["TRUE"]
};
