import 'server-only';

// Answer key for Cambridge IELTS 21 · Academic Reading Test 1, transcribed from
// the owner-supplied material. Matching is case/whitespace-insensitive and
// accepts the listed variants (see grading.ts).
export const answerKey: Record<string, string[]> = {
  "1": ["mining"],
  "2": ["education"],
  "3": ["notes"],
  "4": ["journals"],
  "5": ["Venice"],
  "6": ["canteen"],
  "7": ["friends"],
  "8": ["TRUE"],
  "9": ["NOT GIVEN"],
  "10": ["FALSE"],
  "11": ["NOT GIVEN"],
  "12": ["TRUE"],
  "13": ["TRUE"],
  "14": ["C"],
  "15": ["B"],
  "16": ["A"],
  "17": ["G"],
  "18": ["breath"],
  "19": ["questionnaire"],
  "20": ["wellbeing"],
  "21": ["depression"],
  "22": ["C"],
  "23": ["A"],
  "24": ["B"],
  "25": ["D"],
  "26": ["C"],
  "27": ["B"],
  "28": ["A"],
  "29": ["C"],
  "30": ["A"],
  "31": ["H"],
  "32": ["E"],
  "33": ["I"],
  "34": ["A"],
  "35": ["G"],
  "36": ["C"],
  "37": ["YES"],
  "38": ["NOT GIVEN"],
  "39": ["NO"],
  "40": ["YES"]
};
