import 'server-only';

// Answer key for Cambridge IELTS 19 · Academic Reading Test 3, transcribed from
// the owner-supplied material. Matching is case/whitespace-insensitive and
// accepts the listed variants (see grading.ts).
export const answerKey: Record<string, string[]> = {
  "1": ["FALSE"],
  "2": ["FALSE"],
  "3": ["TRUE"],
  "4": ["NOT GIVEN"],
  "5": ["TRUE"],
  "6": ["NOT GIVEN"],
  "7": ["FALSE"],
  "8": ["caves"],
  "9": ["stone"],
  "10": ["bones"],
  "11": ["beads"],
  "12": ["pottery"],
  "13": ["spices"],
  "14": ["G"],
  "15": ["A"],
  "16": ["H"],
  "17": ["B"],
  "18": ["carbon"],
  "19": ["fires"],
  "20": ["biodiversity"],
  "21": ["ditches"],
  "22": ["subsidence"],
  "23": ["A"],
  "24": ["C"],
  "25": ["D"],
  "26": ["B"],
  "27": ["D"],
  "28": ["A"],
  "29": ["C"],
  "30": ["B"],
  "31": ["C"],
  "32": ["E"],
  "33": ["F"],
  "34": ["B"],
  "35": ["NO"],
  "36": ["YES"],
  "37": ["NO"],
  "38": ["NOT GIVEN"],
  "39": ["NOT GIVEN"],
  "40": ["YES"]
};
