import 'server-only';

// Answer key for Cambridge IELTS 18 · Academic Reading Test 2, transcribed from
// the owner-supplied material. Matching is case/whitespace-insensitive and
// accepts the listed variants (see grading.ts).
export const answerKey: Record<string, string[]> = {
  "1": ["antlers", "deer antlers"],
  "2": ["posts", "timber posts"],
  "3": ["tree trunks"],
  "4": ["oxen"],
  "5": ["glaciers"],
  "6": ["druids"],
  "7": ["burial"],
  "8": ["calendar"],
  "9": ["TRUE"],
  "10": ["FALSE"],
  "11": ["FALSE"],
  "12": ["TRUE"],
  "13": ["NOT GIVEN"],
  "14": ["C"],
  "15": ["A"],
  "16": ["B"],
  "17": ["D"],
  "18": ["C"],
  "19": ["D"],
  "20": ["YES"],
  "21": ["NOT GIVEN"],
  "22": ["NO"],
  "23": ["YES"],
  "24": ["C"],
  "25": ["A"],
  "26": ["E"],
  "27": ["NOT GIVEN"],
  "28": ["NOT GIVEN"],
  "29": ["TRUE"],
  "30": ["FALSE"],
  "31": ["TRUE"],
  "32": ["NOT GIVEN"],
  "33": ["FALSE"],
  "34": ["transport"],
  "35": ["staircases"],
  "36": ["engineering"],
  "37": ["rule"],
  "38": ["Roman"],
  "39": ["Paris"],
  "40": ["outwards"]
};
