import 'server-only';

// Answer key for Cambridge IELTS 11 · Listening Test 1, transcribed from the
// owner-supplied material. Matching is case/whitespace-insensitive and accepts
// the listed variants (see ielts-reading/grading.ts).
export const answerKey: Record<string, string[]> = {
  "1": ["Charlton"],
  "2": ["115"],
  "3": ["cash"],
  "4": ["parking"],
  "5": ["music"],
  "6": ["entry"],
  "7": ["stage"],
  "8": ["code"],
  "9": ["floor", "floors"],
  "10": ["decoration", "decorations"],
  "11": ["animal", "animals"],
  "12": ["tool", "tools"],
  "13": ["shoes"],
  "14": ["dog", "dogs"],
  "15": ["F"],
  "16": ["G"],
  "17": ["D"],
  "18": ["H"],
  "19": ["C"],
  "20": ["A"],
  "21": ["C"],
  "22": ["B"],
  "23": ["B"],
  "24": ["C"],
  "25": ["A"],
  "26": ["B"],
  "27": ["C"],
  "28": ["A"],
  "29": ["B"],
  "30": ["A"],
  "31": ["conservation"],
  "32": ["food", "foods"],
  "33": ["surface"],
  "34": ["oxygen", "O2"],
  "35": ["mammals"],
  "36": ["ice"],
  "37": ["decline", "declining", "decrease"],
  "38": ["map"],
  "39": ["migration"],
  "40": ["consumption"]
};
