import 'server-only';

// Answer key for Cambridge IELTS 13 · Listening Test 2, transcribed from the
// owner-supplied material. Matching is case/whitespace-insensitive and accepts
// the listed variants (see ielts-reading/grading.ts).
export const answerKey: Record<string, string[]> = {
  "1": ["races"],
  "2": ["insurance"],
  "3": ["Jerriz"],
  "4": ["25", "twenty-five"],
  "5": ["stadium"],
  "6": ["park"],
  "7": ["coffee"],
  "8": ["leader"],
  "9": ["route"],
  "10": ["lights"],
  "11": ["C"],
  "12": ["B"],
  "13": ["C"],
  "14": ["B"],
  "15": ["B"],
  "16": ["A"],
  "17": ["C", "E"],
  "18": ["C", "E"],
  "19": ["B", "D"],
  "20": ["B", "D"],
  "21": ["B"],
  "22": ["A"],
  "23": ["C"],
  "24": ["C"],
  "25": ["A"],
  "26": ["A"],
  "27": ["C"],
  "28": ["D"],
  "29": ["G"],
  "30": ["B"],
  "31": ["location"],
  "32": ["world"],
  "33": ["personal"],
  "34": ["attention"],
  "35": ["name"],
  "36": ["network"],
  "37": ["frequency"],
  "38": ["colour", "color"],
  "39": ["brain"],
  "40": ["self"]
};
