import 'server-only';

// Answer key for Cambridge IELTS 12 · Listening Test 2, transcribed from the
// owner-supplied material. Matching is case/whitespace-insensitive and accepts
// the listed variants (see ielts-reading/grading.ts).
export const answerKey: Record<string, string[]> = {
  "1": ["2.45", "2:45"],
  "2": ["band"],
  "3": ["play"],
  "4": ["scientist"],
  "5": ["river"],
  "6": ["grandparents"],
  "7": ["Handsworth"],
  "8": ["traditional"],
  "9": ["outdoor"],
  "10": ["logo"],
  "11": ["B"],
  "12": ["C"],
  "13": ["A"],
  "14": ["B"],
  "15": ["C"],
  "16": ["F"],
  "17": ["B"],
  "18": ["E"],
  "19": ["G"],
  "20": ["C"],
  "21": ["C"],
  "22": ["B"],
  "23": ["C"],
  "24": ["A"],
  "25": ["C"],
  "26": ["E"],
  "27": ["G"],
  "28": ["D"],
  "29": ["C"],
  "30": ["A"],
  "31": ["bullying"],
  "32": ["superiority"],
  "33": ["personality"],
  "34": ["structural"],
  "35": ["absence"],
  "36": ["confidence"],
  "37": ["visions"],
  "38": ["democratic"],
  "39": ["respect"],
  "40": ["mediator"]
};
