import 'server-only';

// Answer key for Cambridge IELTS 14 · Listening Test 1, transcribed from the
// owner-supplied material. Matching is case/whitespace-insensitive and accepts
// the listed variants (see ielts-reading/grading.ts).
export const answerKey: Record<string, string[]> = {
  "1": ["Canadian"],
  "2": ["furniture"],
  "3": ["Park"],
  "4": ["250"],
  "5": ["phone"],
  "6": ["10", "10th"],
  "7": ["museum"],
  "8": ["time"],
  "9": ["blond", "blonde"],
  "10": ["87954 82361", "8795482361"],
  "11": ["A", "C"],
  "12": ["A", "C"],
  "13": ["B", "E"],
  "14": ["B", "E"],
  "15": ["B"],
  "16": ["B"],
  "17": ["C"],
  "18": ["A"],
  "19": ["A"],
  "20": ["C"],
  "21": ["B"],
  "22": ["A"],
  "23": ["C"],
  "24": ["B"],
  "25": ["A"],
  "26": ["B"],
  "27": ["A"],
  "28": ["F"],
  "29": ["G"],
  "30": ["C"],
  "31": ["industry"],
  "32": ["constant"],
  "33": ["direction"],
  "34": ["floor"],
  "35": ["predictable"],
  "36": ["bay"],
  "37": ["gates"],
  "38": ["fuel"],
  "39": ["jobs"],
  "40": ["migration"]
};
