import 'server-only';

// Answer key for Cambridge IELTS 12 · Listening Test 4, transcribed from the
// owner-supplied material. Matching is case/whitespace-insensitive and accepts
// the listed variants (see ielts-reading/grading.ts).
export const answerKey: Record<string, string[]> = {
  "1": ["temporary"],
  "2": ["doctor"],
  "3": ["Africa"],
  "4": ["youth"],
  "5": ["May"],
  "6": ["cheese"],
  "7": ["Arbuthnot"],
  "8": ["DG7 4PH"],
  "9": ["Tuesday"],
  "10": ["talk"],
  "11": ["A"],
  "12": ["C"],
  "13": ["B"],
  "14": ["B"],
  "15": ["H"],
  "16": ["C"],
  "17": ["F"],
  "18": ["G"],
  "19": ["I"],
  "20": ["B"],
  "21": ["classification"],
  "22": ["worst"],
  "23": ["slides"],
  "24": ["issues"],
  "25": ["F"],
  "26": ["A"],
  "27": ["E"],
  "28": ["C"],
  "29": ["G"],
  "30": ["B"],
  "31": ["garden", "gardens"],
  "32": ["political"],
  "33": ["work", "study"],
  "34": ["fountain"],
  "35": ["social"],
  "36": ["lively"],
  "37": ["training"],
  "38": ["culture"],
  "39": ["nature"],
  "40": ["silent"]
};
