import 'server-only';

// Answer key for Cambridge IELTS 14 · Listening Test 2, transcribed from the
// owner-supplied material. Matching is case/whitespace-insensitive and accepts
// the listed variants (see ielts-reading/grading.ts).
export const answerKey: Record<string, string[]> = {
  "1": ["219 442 9785", "2194429785"],
  "2": ["10 October", "10th October", "October 10", "October 10th"],
  "3": ["manager"],
  "4": ["Cawley"],
  "5": ["knee"],
  "6": ["3 weeks", "three weeks"],
  "7": ["tennis"],
  "8": ["running"],
  "9": ["shoulder"],
  "10": ["vitamins"],
  "11": ["B"],
  "12": ["C"],
  "13": ["C"],
  "14": ["B"],
  "15": ["A"],
  "16": ["H"],
  "17": ["D"],
  "18": ["F"],
  "19": ["A"],
  "20": ["E"],
  "21": ["B"],
  "22": ["C"],
  "23": ["A"],
  "24": ["A"],
  "25": ["E"],
  "26": ["D"],
  "27": ["A"],
  "28": ["H"],
  "29": ["G"],
  "30": ["C"],
  "31": ["dances"],
  "32": ["survival"],
  "33": ["clouds"],
  "34": ["festivals"],
  "35": ["comets"],
  "36": ["sky"],
  "37": ["instruments"],
  "38": ["thermometer"],
  "39": ["storms"],
  "40": ["telegraph"]
};
